USE [Mag]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[Country] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[female names]    Script Date: 06.08.2023 19:34:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[female names](
	[column1] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 06.08.2023 19:34:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nchar](15) NULL,
	[category] [nchar](10) NULL,
	[price] [float] NULL,
	[discount] [int] NULL,
	[quantity] [int] NULL,
	[measurement] [nchar](10) NULL,
	[producer] [nchar](10) NULL,
	[country] [nchar](10) NULL,
	[supplier] [nchar](10) NULL,
	[date_of_delivery] [date] NULL,
	[expire_date] [date] NULL,
 CONSTRAINT [PK_Product_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Country] ([Country]) VALUES (N'Afghanistan (AF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Åland Islands (AX)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Albania (AL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Algeria (DZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'American Samoa (AS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Andorra (AD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Angola (AO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Anguilla (AI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Antarctica (AQ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Antigua & Barbuda (AG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Argentina (AR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Armenia (AM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Aruba (AW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Australia (AU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Austria (AT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Azerbaijan (AZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bahamas (BS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bahrain (BH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bangladesh (BD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Barbados (BB)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Belarus (BY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Belgium (BE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Belize (BZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Benin (BJ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bermuda (BM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bhutan (BT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bolivia (BO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bosnia & Herzegovina (BA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Botswana (BW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bouvet Island (BV)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Brazil (BR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'British Indian Ocean Territory (IO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'British Virgin Islands (VG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Brunei (BN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Bulgaria (BG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Burkina Faso (BF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Burundi (BI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cambodia (KH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cameroon (CM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Canada (CA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cape Verde (CV)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Caribbean Netherlands (BQ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cayman Islands (KY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Central African Republic (CF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Chad (TD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Chile (CL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'China (CN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Christmas Island (CX)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cocos (Keeling) Islands (CC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Colombia (CO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Comoros (KM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Congo - Brazzaville (CG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Congo - Kinshasa (CD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cook Islands (CK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Costa Rica (CR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Côte d’Ivoire (CI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Croatia (HR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cuba (CU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Curaçao (CW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Cyprus (CY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Czechia (CZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Denmark (DK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Djibouti (DJ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Dominica (DM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Dominican Republic (DO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Ecuador (EC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Egypt (EG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'El Salvador (SV)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Equatorial Guinea (GQ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Eritrea (ER)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Estonia (EE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Eswatini (SZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Ethiopia (ET)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Falkland Islands (FK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Faroe Islands (FO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Fiji (FJ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Finland (FI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'France (FR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'French Guiana (GF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'French Polynesia (PF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'French Southern Territories (TF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Gabon (GA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Gambia (GM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Georgia (GE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Germany (DE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Ghana (GH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Gibraltar (GI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Greece (GR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Greenland (GL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Grenada (GD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guadeloupe (GP)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guam (GU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guatemala (GT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guernsey (GG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guinea (GN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guinea-Bissau (GW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Guyana (GY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Haiti (HT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Heard & McDonald Islands (HM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Honduras (HN)')
GO
INSERT [dbo].[Country] ([Country]) VALUES (N'Hong Kong SAR China (HK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Hungary (HU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Iceland (IS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'India (IN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Indonesia (ID)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Iran (IR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Iraq (IQ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Ireland (IE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Isle of Man (IM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Israel (IL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Italy (IT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Jamaica (JM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Japan (JP)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Jersey (JE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Jordan (JO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Kazakhstan (KZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Kenya (KE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Kiribati (KI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Kuwait (KW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Kyrgyzstan (KG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Laos (LA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Latvia (LV)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Lebanon (LB)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Lesotho (LS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Liberia (LR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Libya (LY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Liechtenstein (LI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Lithuania (LT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Luxembourg (LU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Macao SAR China (MO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Madagascar (MG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Malawi (MW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Malaysia (MY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Maldives (MV)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mali (ML)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Malta (MT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Marshall Islands (MH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Martinique (MQ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mauritania (MR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mauritius (MU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mayotte (YT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mexico (MX)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Micronesia (FM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Moldova (MD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Monaco (MC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mongolia (MN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Montenegro (ME)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Montserrat (MS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Morocco (MA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Mozambique (MZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Myanmar (Burma) (MM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Namibia (NA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Nauru (NR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Nepal (NP)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Netherlands (NL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'New Caledonia (NC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'New Zealand (NZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Nicaragua (NI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Niger (NE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Nigeria (NG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Niue (NU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Norfolk Island (NF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'North Korea (KP)')
INSERT [dbo].[Country] ([Country]) VALUES (N'North Macedonia (MK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Northern Mariana Islands (MP)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Norway (NO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Oman (OM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Pakistan (PK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Palau (PW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Palestinian Territories (PS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Panama (PA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Papua New Guinea (PG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Paraguay (PY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Peru (PE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Philippines (PH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Pitcairn Islands (PN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Poland (PL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Portugal (PT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Puerto Rico (PR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Qatar (QA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Réunion (RE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Romania (RO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Russia (RU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Rwanda (RW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Samoa (WS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'San Marino (SM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'São Tomé & Príncipe (ST)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Saudi Arabia (SA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Senegal (SN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Serbia (RS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Seychelles (SC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Sierra Leone (SL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Singapore (SG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Sint Maarten (SX)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Slovakia (SK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Slovenia (SI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Solomon Islands (SB)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Somalia (SO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'South Africa (ZA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'South Georgia & South Sandwich Islands (GS)')
GO
INSERT [dbo].[Country] ([Country]) VALUES (N'South Korea (KR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'South Sudan (SS)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Spain (ES)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Sri Lanka (LK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Barthélemy (BL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Helena (SH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Kitts & Nevis (KN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Lucia (LC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Martin (MF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Pierre & Miquelon (PM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'St. Vincent & Grenadines (VC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Sudan (SD)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Suriname (SR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Svalbard & Jan Mayen (SJ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Sweden (SE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Switzerland (CH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Syria (SY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Taiwan (TW)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Tajikistan (TJ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Tanzania (TZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Thailand (TH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Timor-Leste (TL)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Togo (TG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Tokelau (TK)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Tonga (TO)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Trinidad & Tobago (TT)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Tunisia (TN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Turkey (TR)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Turkmenistan (TM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Turks & Caicos Islands (TC)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Tuvalu (TV)')
INSERT [dbo].[Country] ([Country]) VALUES (N'U.S. Outlying Islands (UM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'U.S. Virgin Islands (VI)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Uganda (UG)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Ukraine (UA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'United Arab Emirates (AE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'United Kingdom (GB)')
INSERT [dbo].[Country] ([Country]) VALUES (N'United States (US)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Uruguay (UY)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Uzbekistan (UZ)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Vanuatu (VU)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Vatican City (VA)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Venezuela (VE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Vietnam (VN)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Wallis & Futuna (WF)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Western Sahara (EH)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Yemen (YE)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Zambia (ZM)')
INSERT [dbo].[Country] ([Country]) VALUES (N'Zimbabwe (ZW)')
GO
INSERT [dbo].[female names] ([column1]) VALUES (N'�������')
INSERT [dbo].[female names] ([column1]) VALUES (N'������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����')
INSERT [dbo].[female names] ([column1]) VALUES (N'���������')
INSERT [dbo].[female names] ([column1]) VALUES (N'���')
INSERT [dbo].[female names] ([column1]) VALUES (N'����')
INSERT [dbo].[female names] ([column1]) VALUES (N'��������')
INSERT [dbo].[female names] ([column1]) VALUES (N'����������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����������')
GO
INSERT [dbo].[female names] ([column1]) VALUES (N'����')
INSERT [dbo].[female names] ([column1]) VALUES (N'�������')
INSERT [dbo].[female names] ([column1]) VALUES (N'��������')
INSERT [dbo].[female names] ([column1]) VALUES (N'������')
INSERT [dbo].[female names] ([column1]) VALUES (N'������������')
INSERT [dbo].[female names] ([column1]) VALUES (N'����������')
INSERT [dbo].[female names] ([column1]) VALUES (N'���������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����')
INSERT [dbo].[female names] ([column1]) VALUES (N'���')
GO
INSERT [dbo].[female names] ([column1]) VALUES (N'����')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����')
INSERT [dbo].[female names] ([column1]) VALUES (N'���')
INSERT [dbo].[female names] ([column1]) VALUES (N'�������')
INSERT [dbo].[female names] ([column1]) VALUES (N'������')
INSERT [dbo].[female names] ([column1]) VALUES (N'��������')
INSERT [dbo].[female names] ([column1]) VALUES (N'����������')
INSERT [dbo].[female names] ([column1]) VALUES (N'���������')
GO
INSERT [dbo].[female names] ([column1]) VALUES (N'��������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����')
INSERT [dbo].[female names] ([column1]) VALUES (N'�������')
INSERT [dbo].[female names] ([column1]) VALUES (N'���������')
INSERT [dbo].[female names] ([column1]) VALUES (N'������')
INSERT [dbo].[female names] ([column1]) VALUES (N'����')
INSERT [dbo].[female names] ([column1]) VALUES (N'����������')
GO
INSERT [dbo].[female names] ([column1]) VALUES (N'����')
INSERT [dbo].[female names] ([column1]) VALUES (N'������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����')
INSERT [dbo].[female names] ([column1]) VALUES (N'����������')
INSERT [dbo].[female names] ([column1]) VALUES (N'��������')
INSERT [dbo].[female names] ([column1]) VALUES (N'���')
INSERT [dbo].[female names] ([column1]) VALUES (N'���������')
INSERT [dbo].[female names] ([column1]) VALUES (N'�����������')
GO
SET IDENTITY_INSERT [dbo].[Product] ON 

INSERT [dbo].[Product] ([id], [name], [category], [price], [discount], [quantity], [measurement], [producer], [country], [supplier], [date_of_delivery], [expire_date]) VALUES (61, NULL, NULL, 1, 1, NULL, NULL, N'dasdasd   ', NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Product] OFF
GO
